# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\act\OneDrive\Desktop\Harshit\RealTime_weapon_Detection\pyqt_user_app\UI\detection_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 530)
        MainWindow.setMaximumSize(QtCore.QSize(874, 530))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_detection = QtWidgets.QLabel(self.centralwidget)
        self.label_detection.setGeometry(QtCore.QRect(10, 10, 854, 480))
        self.label_detection.setMaximumSize(QtCore.QSize(1000, 1000))
        self.label_detection.setAutoFillBackground(True)
        self.label_detection.setText("")
        self.label_detection.setObjectName("label_detection")
        self.stop_detection_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_detection_button.setGeometry(QtCore.QRect(362, 495, 150, 32))
        self.stop_detection_button.setObjectName("stop_detection_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weapon Detection"))
        self.stop_detection_button.setText(_translate("MainWindow", "Stop Monitoring"))
