# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\act\OneDrive\Desktop\Harshit\RealTime_weapon_Detection\pyqt_user_app\UI\settings_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 300)
        MainWindow.setMinimumSize(QtCore.QSize(300, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 241, 71))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.location_input = QtWidgets.QLineEdit(self.centralwidget)
        self.location_input.setGeometry(QtCore.QRect(30, 125, 240, 21))
        self.location_input.setObjectName("location_input")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 250, 240, 32))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 156, 211, 16))
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 101, 121, 16))
        self.label.setObjectName("label")
        self.sendTo_input = QtWidgets.QLineEdit(self.centralwidget)
        self.sendTo_input.setGeometry(QtCore.QRect(30, 180, 240, 21))
        self.sendTo_input.setObjectName("sendTo_input")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weapon Detection"))
        self.label_2.setText(_translate("MainWindow", "Enter camera\'s location and email address."))
        self.pushButton.setText(_translate("MainWindow", "Start Monitoring"))
        self.label_3.setText(_translate("MainWindow", "Email address:"))
        self.label.setText(_translate("MainWindow", "Camera\'s location:"))
